### PR TITLE
DataHub doc structure first draft

### PR DESCRIPTION
**Pull request by floradanna**
DataHub doc structure first draft

### CODE REVIEW

**Comment by floradanna** [comment]
@bedroesb I made a change in the gemfile to be able to work locally. Should I have had reverted it back before pushing changes?

**Comment by bedroesb** [comment]
Hey flora, looking good, do we close this branch PR and branch? https://github.com/ELIXIR-Belgium/DataHub-help-test/pull/2/

**Comment by bedroesb** [comment]
the change is gemfile is fine, I quickly updated it to a less specific one (these are minor versions and this way we keep compatibility)

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
congratz btw on all the restructuring

**Comment by floradanna** [comment]
> Hey flora, looking good, do we close this branch PR and branch? #2

Not yet, please.

**Comment by bedroesb** [comment]
Hope it was clear that I meant the other open PR, not this one :)

**Pull request merged**
