### PR TITLE
Add datahub in header

### PR DESCRIPTION
**Pull request by bedroesb**

### CODE REVIEW

**Comment by bedroesb** [comment]
@floradanna

**Comment by floradanna** [comment]
Thanks! The image seems a bit blurry though, or not?

**Comment by bedroesb** [comment]
I took the exact same one from datahub :)

**Comment by bedroesb** [comment]
Screenshot from 2023-03-16 09-27-17

**Comment by floradanna** [comment]
ok. thanks. We will fix both later then.

**Review by floradanna — APPROVED** [review]

**Comment by bedroesb** [comment]
svg is the way ;)

**Pull request merged**
